### ISSUE TITLE
Question: asset-manifest

### ISSUE THREAD

**Issue by federicobarera** [sergeysolovev/webpack-aspnetcore#13]
Create React App scaffolds a webpack config that roughly translates to the following assets_manifest.json

```
{
  "main.js": "/static/js/main.46992962.chunk.js",
  "main.js.map": "/static/js/main.46992962.chunk.js.map",
  "static/css/1.c39d6716.chunk.css": "/static/css/1.c39d6716.chunk.css",
  "static/js/1.92a172e3.chunk.js": "/static/js/1.92a172e3.chunk.js",
  "static/js/1.92a172e3.chunk.js.map": "/static/js/1.92a172e3.chunk.js.map",
  "runtime~main.js": "/static/js/runtime~main.229c360f.js",
  "runtime~main.js.map": "/static/js/runtime~main.229c360f.js.map",
  "static/css/1.c39d6716.chunk.css.map": "/static/css/1.c39d6716.chunk.css.map",
  "index.html": "/index.html",
  "precache-manifest.77a7f09e11c7b0b373144b7dc071abbe.js": "/precache-manifest.77a7f09e11c7b0b373144b7dc071abbe.js",
  "service-worker.js": "/service-worker.js"
}
```

Does the project supports the following:

1. Automatic runtime~ injection when "main.js" is referenced.
2. Dynamic chunks inclusions.

Thanks

**Comment by sergeysolovev** [comment]
Hey @federicobarera,

It’s not supported. In your case I suggest you to use Node.js instead of ASP.NET Core to serve (or prerender) static content. I recommend to use [loadable-components](https://github.com/smooth-code/loadable-components) for painless server-side rendering. Hope it’ll be helpful enough.
