### ISSUE TITLE
WebpackApplicationBuilderExtensions.UseWebpack not an extension method

### ISSUE THREAD

**Issue by PerfectlyNormal** [sergeysolovev/webpack-aspnetcore#8]
Hi

I've been using this project a little while now, and it works very well.

One thing I had a bit of trouble figuring out was why `UseWebpack` wasn't an extension method? Now I'm forced to use it like `WebpackApplicationBuilderExtensions.UseWebpack(app, withDevServer: env.IsDevelopment());`, instead of the more common `app.UseWebpack(withDevServer: env.IsDevelopment());`

Is there any particular reason, or just an oversight?

**Comment by sergeysolovev** [comment]
@PerfectlyNormal 

Hello! Thanks you for your feedback! It was intended to work as an extension method, but there seems to be a typo.

I think the reason is missed `this` before the first parameter in the line

```
public static IApplicationBuilder UseWebpack(IApplicationBuilder app, bool withDevServer)
```

https://github.com/sergeysolovev/webpack-aspnetcore/blob/master/src/Webpack.AspNetCore/Extensions/WebpackApplicationBuilderExtensions.cs#L18

I would love to see a PR fixing this typo.
